
#ifndef EQP_DEFINES_TRILOGY_H
#define EQP_DEFINES_TRILOGY_H

#define EQP_TRILOGY_MAX_BUFFS               15
#define EQP_TRILOGY_SKILLS_COUNT            74
#define EQP_TRILOGY_LANGUAGES_COUNT         24
#define EQP_TRILOGY_SPELLBOOK_SLOT_COUNT    256
#define EQP_TRILOGY_MEMMED_SPELL_SLOT_COUNT 8

#endif//EQP_DEFINES_TRILOGY_H
