
#ifndef EQP_SOURCE_ID_H
#define EQP_SOURCE_ID_H

#define EQP_SOURCE_ID_ZONE_CLUSTER_OFFSET   10000
#define EQP_SOURCE_ID_PROCESS_OFFSET        20000
#define EQP_SOURCE_ID_MASTER                (EQP_SOURCE_ID_PROCESS_OFFSET + 1)
#define EQP_SOURCE_ID_CHAR_SELECT           (EQP_SOURCE_ID_PROCESS_OFFSET + 2)
#define EQP_SOURCE_ID_LOGIN                 (EQP_SOURCE_ID_PROCESS_OFFSET + 3)
#define EQP_SOURCE_ID_LOG_WRITER            (EQP_SOURCE_ID_PROCESS_OFFSET + 4)
#define EQP_SOURCE_ID_CONSOLE               (EQP_SOURCE_ID_PROCESS_OFFSET + 5)

#endif//EQP_SOURCE_ID_H
