
#ifndef EQP_SOURCE_ID_H
#define EQP_SOURCE_ID_H

#define EQP_SOURCE_ID_ZONE_INSTANCE_OFFSET  1000    /* E.g.: 2054 is instance 2 of zone 54; max instance id is 999*/
#define EQP_SOURCE_ID_ZONE_CLUSTER_OFFSET   1000000
#define EQP_SOURCE_ID_PROCESS_OFFSET        2000000
#define EQP_SOURCE_ID_MASTER                (EQP_SOURCE_ID_PROCESS_OFFSET + 1)
#define EQP_SOURCE_ID_CHAR_SELECT           (EQP_SOURCE_ID_PROCESS_OFFSET + 2)
#define EQP_SOURCE_ID_LOGIN                 (EQP_SOURCE_ID_PROCESS_OFFSET + 3)
#define EQP_SOURCE_ID_LOG_WRITER            (EQP_SOURCE_ID_PROCESS_OFFSET + 4)
#define EQP_SOURCE_ID_CONSOLE               (EQP_SOURCE_ID_PROCESS_OFFSET + 5)

#define EQP_SOURCE_ID_ZONE_MAX              (EQP_SOURCE_ID_ZONE_INSTANCE_OFFSET - 1)
#define EQP_SOURCE_ID_ZONE_INSTANCE_MAX     ((EQP_SOURCE_ID_ZONE_CLUSTER_OFFSET / EQP_SOURCE_ID_ZONE_INSTANCE_OFFSET) - 1)

#endif//EQP_SOURCE_ID_H
