
#include "zone_id.h"

ZoneShortNameMap* zone_short_name_map_create(Basic* basic)
{
    ZoneShortNameMap* map = hash_table_create_type(basic, int);
    int zoneId;

#define add(id, name) zoneId = id; hash_table_set_by_cstr(basic, &map, name, sizeof(name) - 1, &zoneId)
    
    add(  1, "qeynos");
    add(  2, "qeynos2");
    add(  3, "qrg");
    add(  4, "qeytoqrg");
    add(  5, "highpass");
    add(  6, "highkeep");
    add(  8, "freportn");
    add(  9, "freportw");
    add( 10, "freporte");
    add( 11, "runnyeye");
    add( 12, "qey2hh1");
    add( 13, "northkarana");
    add( 14, "southkarana");
    add( 15, "eastkarana");
    add( 16, "beholder");
    add( 17, "blackburrow");
    add( 18, "paw");
    add( 19, "rivervale");
    add( 20, "kithicor");
    add( 21, "commons");
    add( 22, "ecommons");
    add( 23, "erudnint");
    add( 24, "erudnext");
    add( 25, "nektulos");
    add( 25, "nektulos");
    add( 26, "cshome");
    add( 27, "lavastorm");
    add( 28, "nektropos");
    add( 29, "halas");
    add( 30, "everfrost");
    add( 31, "soldunga");
    add( 32, "soldungb");
    add( 33, "misty");
    add( 34, "nro");
    add( 35, "sro");
    add( 36, "befallen");
    add( 37, "oasis");
    add( 38, "tox");
    add( 39, "hole");
    add( 40, "neriaka");
    add( 41, "neriakb");
    add( 42, "neriakc");
    add( 43, "neriakd");
    add( 44, "najena");
    add( 45, "qcat");
    add( 46, "innothule");
    add( 47, "feerrott");
    add( 48, "cazicthule");
    add( 49, "oggok");
    add( 50, "rathemtn");
    add( 51, "lakerathe");
    add( 52, "grobb");
    add( 53, "aviak");
    add( 54, "gfaydark");
    add( 55, "akanon");
    add( 56, "steamfont");
    add( 57, "lfaydark");
    add( 58, "crushbone");
    add( 59, "mistmoore");
    add( 60, "kaladima");
    add( 61, "felwithea");
    add( 62, "felwitheb");
    add( 63, "unrest");
    add( 64, "kedge");
    add( 65, "guktop");
    add( 66, "gukbottom");
    add( 67, "kaladimb");
    add( 68, "butcher");
    add( 69, "oot");
    add( 70, "cauldron");
    add( 71, "airplane");
    add( 72, "fearplane");
    add( 73, "permafrost");
    add( 74, "kerraridge");
    add( 75, "paineel");
    add( 76, "hateplane");
    add( 77, "arena");
    add( 78, "fieldofbone");
    add( 79, "warslikswood");
    add( 80, "soltemple");
    add( 81, "droga");
    add( 82, "cabwest");
    add( 83, "swampofnohope");
    add( 84, "firiona");
    add( 85, "lakeofillomen");
    add( 86, "dreadlands");
    add( 87, "burningwood");
    add( 88, "kaesora");
    add( 89, "sebilis");
    add( 90, "citymist");
    add( 91, "skyfire");
    add( 92, "frontiermtns");
    add( 93, "overthere");
    add( 94, "emeraldjungle");
    add( 95, "trakanon");
    add( 96, "timorous");
    add( 97, "kurn");
    add( 98, "erudsxing");
    add(100, "stonebrunt");
    add(101, "warrens");
    add(102, "karnor");
    add(103, "chardok");
    add(104, "dalnir");
    add(105, "charasis");
    add(106, "cabeast");
    add(107, "nurga");
    add(108, "veeshan");
    add(109, "veksar");
    add(110, "iceclad");
    add(111, "frozenshadow");
    add(112, "velketor");
    add(113, "kael");
    add(114, "skyshrine");
    add(115, "thurgadina");
    add(116, "eastwastes");
    add(117, "cobaltscar");
    add(118, "greatdivide");
    add(119, "wakening");
    add(120, "westwastes");
    add(121, "crystal");
    add(123, "necropolis");
    add(124, "templeveeshan");
    add(125, "sirens");
    add(126, "mischiefplane");
    add(127, "growthplane");
    add(128, "sleeper");
    add(129, "thurgadinb");
    add(130, "erudsxing2");
    add(150, "shadowhaven");
    add(151, "bazaar");
    add(151, "bazaar");
    add(152, "nexus");
    add(153, "echo");
    add(154, "acrylia");
    add(155, "sharvahl");
    add(156, "paludal");
    add(157, "fungusgrove");
    add(158, "vexthal");
    add(159, "sseru");
    add(160, "katta");
    add(161, "netherbian");
    add(162, "ssratemple");
    add(163, "griegsend");
    add(164, "thedeep");
    add(165, "shadeweaver");
    add(166, "hollowshade");
    add(167, "grimling");
    add(168, "mseru");
    add(169, "letalis");
    add(170, "twilight");
    add(171, "thegrey");
    add(172, "tenebrous");
    add(173, "maiden");
    add(174, "dawnshroud");
    add(175, "scarlet");
    add(176, "umbral");
    add(179, "akheva");
    add(180, "arena2");
    add(181, "jaggedpine");
    add(182, "nedaria");
    add(183, "tutorial");
    add(184, "load");
    add(185, "load2");
    add(186, "hateplaneb");
    add(187, "shadowrest");
    add(188, "tutoriala");
    add(189, "tutorialb");
    add(190, "clz");
    add(200, "codecay");
    add(201, "pojustice");
    add(202, "poknowledge");
    add(203, "potranquility");
    add(204, "ponightmare");
    add(205, "podisease");
    add(206, "poinnovation");
    add(207, "potorment");
    add(208, "povalor");
    add(209, "bothunder");
    add(210, "postorms");
    add(211, "hohonora");
    add(212, "solrotower");
    add(213, "powar");
    add(214, "potactics");
    add(215, "poair");
    add(216, "powater");
    add(217, "pofire");
    add(218, "poeartha");
    add(219, "potimea");
    add(220, "hohonorb");
    add(221, "nightmareb");
    add(222, "poearthb");
    add(223, "potimeb");
    add(224, "gunthak");
    add(225, "dulak");
    add(226, "torgiran");
    add(227, "nadox");
    add(228, "hatesfury");
    add(229, "guka");
    add(230, "ruja");
    add(231, "taka");
    add(232, "mira");
    add(233, "mmca");
    add(234, "gukb");
    add(235, "rujb");
    add(236, "takb");
    add(237, "mirb");
    add(238, "mmcb");
    add(239, "gukc");
    add(240, "rujc");
    add(241, "takc");
    add(242, "mirc");
    add(243, "mmcc");
    add(244, "gukd");
    add(245, "rujd");
    add(246, "takd");
    add(247, "mird");
    add(248, "mmcd");
    add(249, "guke");
    add(250, "ruje");
    add(251, "take");
    add(252, "mire");
    add(253, "mmce");
    add(254, "gukf");
    add(255, "rujf");
    add(256, "takf");
    add(257, "mirf");
    add(258, "mmcf");
    add(259, "gukg");
    add(260, "rujg");
    add(261, "takg");
    add(262, "mirg");
    add(263, "mmcg");
    add(264, "gukh");
    add(265, "rujh");
    add(266, "takh");
    add(267, "mirh");
    add(268, "mmch");
    add(269, "ruji");
    add(270, "taki");
    add(271, "miri");
    add(272, "mmci");
    add(273, "rujj");
    add(274, "takj");
    add(275, "mirj");
    add(276, "mmcj");
    add(277, "chardokb");
    add(278, "soldungc");
    add(279, "abysmal");
    add(280, "natimbi");
    add(281, "qinimi");
    add(282, "riwwi");
    add(283, "barindu");
    add(284, "ferubi");
    add(285, "snpool");
    add(286, "snlair");
    add(287, "snplant");
    add(288, "sncrematory");
    add(289, "tipt");
    add(290, "vxed");
    add(291, "yxtta");
    add(292, "uqua");
    add(293, "kodtaz");
    add(294, "ikkinz");
    add(295, "qvic");
    add(296, "inktuta");
    add(297, "txevu");
    add(298, "tacvi");
    add(299, "qvicb");
    add(300, "wallofslaughter");
    add(301, "bloodfields");
    add(302, "draniksscar");
    add(303, "causeway");
    add(304, "chambersa");
    add(305, "chambersb");
    add(306, "chambersc");
    add(307, "chambersd");
    add(308, "chamberse");
    add(309, "chambersf");
    add(316, "provinggrounds");
    add(317, "anguish");
    add(318, "dranikhollowsa");
    add(319, "dranikhollowsb");
    add(320, "dranikhollowsc");
    add(328, "dranikcatacombsa");
    add(329, "dranikcatacombsb");
    add(330, "dranikcatacombsc");
    add(331, "draniksewersa");
    add(332, "draniksewersb");
    add(333, "draniksewersc");
    add(334, "riftseekers");
    add(335, "harbingers");
    add(336, "dranik");
    add(337, "broodlands");
    add(338, "stillmoona");
    add(339, "stillmoonb");
    add(340, "thundercrest");
    add(341, "delvea");
    add(342, "delveb");
    add(343, "thenest");
    add(344, "guildlobby");
    add(345, "guildhall");
    add(346, "barter");
    add(347, "illsalin");
    add(348, "illsalina");
    add(349, "illsalinb");
    add(350, "illsalinc");
    add(351, "dreadspire");
    add(354, "drachnidhive");
    add(355, "drachnidhivea");
    add(356, "drachnidhiveb");
    add(357, "drachnidhivec");
    add(358, "westkorlach");
    add(359, "westkorlacha");
    add(360, "westkorlachb");
    add(361, "westkorlachc");
    add(362, "eastkorlach");
    add(363, "eastkorlacha");
    add(364, "shadowspine");
    add(365, "corathus");
    add(366, "corathusa");
    add(367, "corathusb");
    add(368, "nektulosa");
    add(369, "arcstone");
    add(370, "relic");
    add(371, "skylance");
    add(372, "devastation");
    add(373, "devastationa");
    add(374, "rage");
    add(375, "ragea");
    add(376, "takishruins");
    add(377, "takishruinsa");
    add(378, "elddar");
    add(379, "elddara");
    add(380, "theater");
    add(381, "theatera");
    add(382, "freeporteast");
    add(383, "freeportwest");
    add(384, "freeportsewers");
    add(385, "freeportacademy");
    add(386, "freeporttemple");
    add(387, "freeportmilitia");
    add(388, "freeportarena");
    add(389, "freeportcityhall");
    add(390, "freeporttheater");
    add(391, "freeporthall");
    add(392, "northro");
    add(393, "southro");
    add(394, "crescent");
    add(395, "moors");
    add(396, "stonehive");
    add(397, "mesa");
    add(398, "roost");
    add(399, "steppes");
    add(400, "icefall");
    add(401, "valdeholm");
    add(402, "frostcrypt");
    add(403, "sunderock");
    add(404, "vergalid");
    add(405, "direwind");
    add(406, "ashengate");
    add(407, "highpasshold");
    add(408, "commonlands");
    add(409, "oceanoftears");
    add(410, "kithforest");
    add(411, "befallenb");
    add(412, "highpasskeep");
    add(413, "innothuleb");
    add(414, "toxxulia");
    add(415, "mistythicket");
    add(416, "kattacastrum");
    add(417, "thalassius");
    add(418, "atiiki");
    add(419, "zhisza");
    add(420, "silyssar");
    add(421, "solteris");
    add(422, "barren");
    add(423, "buriedsea");
    add(424, "jardelshook");
    add(425, "monkeyrock");
    add(426, "suncrest");
    add(427, "deadbone");
    add(428, "blacksail");
    add(429, "maidensgrave");
    add(430, "redfeather");
    add(431, "shipmvp");
    add(432, "shipmvu");
    add(433, "shippvu");
    add(434, "shipuvu");
    add(435, "shipmvm");
    add(436, "mechanotus");
    add(437, "mansion");
    add(438, "steamfactory");
    add(439, "shipworkshop");
    add(440, "gyrospireb");
    add(441, "gyrospirez");
    add(442, "dragonscale");
    add(443, "lopingplains");
    add(444, "hillsofshade");
    add(445, "bloodmoon");
    add(446, "crystallos");
    add(447, "guardian");
    add(448, "steamfontmts");
    add(449, "cryptofshade");
    add(451, "dragonscaleb");
    add(452, "oldfieldofbone");
    add(453, "oldkaesoraa");
    add(454, "oldkaesorab");
    add(455, "oldkurn");
    add(456, "oldkithicor");
    add(457, "oldcommons");
    add(458, "oldhighpass");
    add(459, "thevoida");
    add(460, "thevoidb");
    add(461, "thevoidc");
    add(462, "thevoidd");
    add(463, "thevoide");
    add(464, "thevoidf");
    add(465, "thevoidg");
    add(466, "oceangreenhills");
    add(467, "oceangreenvillage");
    add(468, "oldblackburrow");
    add(469, "bertoxtemple");
    add(470, "discord");
    add(471, "discordtower");
    add(472, "oldbloodfield");
    add(473, "precipiceofwar");
    add(474, "olddranik");
    add(475, "toskirakk");
    add(476, "korascian");
    add(477, "rathechamber");
    add(480, "brellsrest");
    add(481, "fungalforest");
    add(482, "underquarry");
    add(483, "coolingchamber");
    add(484, "shiningcity");
    add(485, "arthicrex");
    add(486, "foundation");
    add(487, "lichencreep");
    add(488, "pellucid");
    add(489, "stonesnake");
    add(490, "brellstemple");
    add(491, "convorteum");
    add(492, "brellsarena");
    add(493, "weddingchapel");
    add(494, "weddingchapeldark");
    add(495, "dragoncrypt");
    add(700, "feerrott2");
    add(701, "thulehouse1");
    add(702, "thulehouse2");
    add(703, "housegarden");
    add(704, "thulelibrary");
    add(705, "well");
    add(706, "fallen");
    add(707, "morellcastle");
    add(708, "somnium");
    add(709, "alkabormare");
    add(710, "miragulmare");
    add(711, "thuledream");
    add(712, "neighborhood");
    add(724, "argath");
    add(725, "arelis");
    add(726, "sarithcity");
    add(727, "rubak");
    add(728, "beastdomain");
    add(729, "resplendent");
    add(730, "pillarsalra");
    add(731, "windsong");
    add(732, "cityofbronze");
    add(733, "sepulcher");
    add(734, "eastsepulcher");
    add(735, "westsepulcher");
    add(752, "shardslanding");
    add(753, "xorbb");
    add(754, "kaelshard");
    add(755, "eastwastesshard");
    add(756, "crystalshard");
    add(757, "breedinggrounds");
    add(758, "eviltree");
    add(759, "grelleth");
    add(760, "chapterhouse");
    add(996, "arttest");
    add(998, "fhalls");
    add(999, "apprentice");

#undef add
    
    return map;
}

int zone_id_by_short_name(ZoneShortNameMap* map, const char* shortName, uint32_t len)
{
    int* zoneId = hash_table_get_type_by_cstr(map, shortName, len, int);
    return zoneId ? *zoneId : 0;
}

const char* zone_short_name_by_id(int id)
{
    const char* ret;
    
    switch (id)
    {
    default:
    case   1: ret = "qeynos"; break;
    case   2: ret = "qeynos2"; break;
    case   3: ret = "qrg"; break;
    case   4: ret = "qeytoqrg"; break;
    case   5: ret = "highpass"; break;
    case   6: ret = "highkeep"; break;
    case   8: ret = "freportn"; break;
    case   9: ret = "freportw"; break;
    case  10: ret = "freporte"; break;
    case  11: ret = "runnyeye"; break;
    case  12: ret = "qey2hh1"; break;
    case  13: ret = "northkarana"; break;
    case  14: ret = "southkarana"; break;
    case  15: ret = "eastkarana"; break;
    case  16: ret = "beholder"; break;
    case  17: ret = "blackburrow"; break;
    case  18: ret = "paw"; break;
    case  19: ret = "rivervale"; break;
    case  20: ret = "kithicor"; break;
    case  21: ret = "commons"; break;
    case  22: ret = "ecommons"; break;
    case  23: ret = "erudnint"; break;
    case  24: ret = "erudnext"; break;
    case  25: ret = "nektulos"; break;
    case  26: ret = "cshome"; break;
    case  27: ret = "lavastorm"; break;
    case  28: ret = "nektropos"; break;
    case  29: ret = "halas"; break;
    case  30: ret = "everfrost"; break;
    case  31: ret = "soldunga"; break;
    case  32: ret = "soldungb"; break;
    case  33: ret = "misty"; break;
    case  34: ret = "nro"; break;
    case  35: ret = "sro"; break;
    case  36: ret = "befallen"; break;
    case  37: ret = "oasis"; break;
    case  38: ret = "tox"; break;
    case  39: ret = "hole"; break;
    case  40: ret = "neriaka"; break;
    case  41: ret = "neriakb"; break;
    case  42: ret = "neriakc"; break;
    case  43: ret = "neriakd"; break;
    case  44: ret = "najena"; break;
    case  45: ret = "qcat"; break;
    case  46: ret = "innothule"; break;
    case  47: ret = "feerrott"; break;
    case  48: ret = "cazicthule"; break;
    case  49: ret = "oggok"; break;
    case  50: ret = "rathemtn"; break;
    case  51: ret = "lakerathe"; break;
    case  52: ret = "grobb"; break;
    case  53: ret = "aviak"; break;
    case  54: ret = "gfaydark"; break;
    case  55: ret = "akanon"; break;
    case  56: ret = "steamfont"; break;
    case  57: ret = "lfaydark"; break;
    case  58: ret = "crushbone"; break;
    case  59: ret = "mistmoore"; break;
    case  60: ret = "kaladima"; break;
    case  61: ret = "felwithea"; break;
    case  62: ret = "felwitheb"; break;
    case  63: ret = "unrest"; break;
    case  64: ret = "kedge"; break;
    case  65: ret = "guktop"; break;
    case  66: ret = "gukbottom"; break;
    case  67: ret = "kaladimb"; break;
    case  68: ret = "butcher"; break;
    case  69: ret = "oot"; break;
    case  70: ret = "cauldron"; break;
    case  71: ret = "airplane"; break;
    case  72: ret = "fearplane"; break;
    case  73: ret = "permafrost"; break;
    case  74: ret = "kerraridge"; break;
    case  75: ret = "paineel"; break;
    case  76: ret = "hateplane"; break;
    case  77: ret = "arena"; break;
    case  78: ret = "fieldofbone"; break;
    case  79: ret = "warslikswood"; break;
    case  80: ret = "soltemple"; break;
    case  81: ret = "droga"; break;
    case  82: ret = "cabwest"; break;
    case  83: ret = "swampofnohope"; break;
    case  84: ret = "firiona"; break;
    case  85: ret = "lakeofillomen"; break;
    case  86: ret = "dreadlands"; break;
    case  87: ret = "burningwood"; break;
    case  88: ret = "kaesora"; break;
    case  89: ret = "sebilis"; break;
    case  90: ret = "citymist"; break;
    case  91: ret = "skyfire"; break;
    case  92: ret = "frontiermtns"; break;
    case  93: ret = "overthere"; break;
    case  94: ret = "emeraldjungle"; break;
    case  95: ret = "trakanon"; break;
    case  96: ret = "timorous"; break;
    case  97: ret = "kurn"; break;
    case  98: ret = "erudsxing"; break;
    case 100: ret = "stonebrunt"; break;
    case 101: ret = "warrens"; break;
    case 102: ret = "karnor"; break;
    case 103: ret = "chardok"; break;
    case 104: ret = "dalnir"; break;
    case 105: ret = "charasis"; break;
    case 106: ret = "cabeast"; break;
    case 107: ret = "nurga"; break;
    case 108: ret = "veeshan"; break;
    case 109: ret = "veksar"; break;
    case 110: ret = "iceclad"; break;
    case 111: ret = "frozenshadow"; break;
    case 112: ret = "velketor"; break;
    case 113: ret = "kael"; break;
    case 114: ret = "skyshrine"; break;
    case 115: ret = "thurgadina"; break;
    case 116: ret = "eastwastes"; break;
    case 117: ret = "cobaltscar"; break;
    case 118: ret = "greatdivide"; break;
    case 119: ret = "wakening"; break;
    case 120: ret = "westwastes"; break;
    case 121: ret = "crystal"; break;
    case 123: ret = "necropolis"; break;
    case 124: ret = "templeveeshan"; break;
    case 125: ret = "sirens"; break;
    case 126: ret = "mischiefplane"; break;
    case 127: ret = "growthplane"; break;
    case 128: ret = "sleeper"; break;
    case 129: ret = "thurgadinb"; break;
    case 130: ret = "erudsxing2"; break;
    case 150: ret = "shadowhaven"; break;
    case 151: ret = "bazaar"; break;
    case 152: ret = "nexus"; break;
    case 153: ret = "echo"; break;
    case 154: ret = "acrylia"; break;
    case 155: ret = "sharvahl"; break;
    case 156: ret = "paludal"; break;
    case 157: ret = "fungusgrove"; break;
    case 158: ret = "vexthal"; break;
    case 159: ret = "sseru"; break;
    case 160: ret = "katta"; break;
    case 161: ret = "netherbian"; break;
    case 162: ret = "ssratemple"; break;
    case 163: ret = "griegsend"; break;
    case 164: ret = "thedeep"; break;
    case 165: ret = "shadeweaver"; break;
    case 166: ret = "hollowshade"; break;
    case 167: ret = "grimling"; break;
    case 168: ret = "mseru"; break;
    case 169: ret = "letalis"; break;
    case 170: ret = "twilight"; break;
    case 171: ret = "thegrey"; break;
    case 172: ret = "tenebrous"; break;
    case 173: ret = "maiden"; break;
    case 174: ret = "dawnshroud"; break;
    case 175: ret = "scarlet"; break;
    case 176: ret = "umbral"; break;
    case 179: ret = "akheva"; break;
    case 180: ret = "arena2"; break;
    case 181: ret = "jaggedpine"; break;
    case 182: ret = "nedaria"; break;
    case 183: ret = "tutorial"; break;
    case 184: ret = "load"; break;
    case 185: ret = "load2"; break;
    case 186: ret = "hateplaneb"; break;
    case 187: ret = "shadowrest"; break;
    case 188: ret = "tutoriala"; break;
    case 189: ret = "tutorialb"; break;
    case 190: ret = "clz"; break;
    case 200: ret = "codecay"; break;
    case 201: ret = "pojustice"; break;
    case 202: ret = "poknowledge"; break;
    case 203: ret = "potranquility"; break;
    case 204: ret = "ponightmare"; break;
    case 205: ret = "podisease"; break;
    case 206: ret = "poinnovation"; break;
    case 207: ret = "potorment"; break;
    case 208: ret = "povalor"; break;
    case 209: ret = "bothunder"; break;
    case 210: ret = "postorms"; break;
    case 211: ret = "hohonora"; break;
    case 212: ret = "solrotower"; break;
    case 213: ret = "powar"; break;
    case 214: ret = "potactics"; break;
    case 215: ret = "poair"; break;
    case 216: ret = "powater"; break;
    case 217: ret = "pofire"; break;
    case 218: ret = "poeartha"; break;
    case 219: ret = "potimea"; break;
    case 220: ret = "hohonorb"; break;
    case 221: ret = "nightmareb"; break;
    case 222: ret = "poearthb"; break;
    case 223: ret = "potimeb"; break;
    case 224: ret = "gunthak"; break;
    case 225: ret = "dulak"; break;
    case 226: ret = "torgiran"; break;
    case 227: ret = "nadox"; break;
    case 228: ret = "hatesfury"; break;
    case 229: ret = "guka"; break;
    case 230: ret = "ruja"; break;
    case 231: ret = "taka"; break;
    case 232: ret = "mira"; break;
    case 233: ret = "mmca"; break;
    case 234: ret = "gukb"; break;
    case 235: ret = "rujb"; break;
    case 236: ret = "takb"; break;
    case 237: ret = "mirb"; break;
    case 238: ret = "mmcb"; break;
    case 239: ret = "gukc"; break;
    case 240: ret = "rujc"; break;
    case 241: ret = "takc"; break;
    case 242: ret = "mirc"; break;
    case 243: ret = "mmcc"; break;
    case 244: ret = "gukd"; break;
    case 245: ret = "rujd"; break;
    case 246: ret = "takd"; break;
    case 247: ret = "mird"; break;
    case 248: ret = "mmcd"; break;
    case 249: ret = "guke"; break;
    case 250: ret = "ruje"; break;
    case 251: ret = "take"; break;
    case 252: ret = "mire"; break;
    case 253: ret = "mmce"; break;
    case 254: ret = "gukf"; break;
    case 255: ret = "rujf"; break;
    case 256: ret = "takf"; break;
    case 257: ret = "mirf"; break;
    case 258: ret = "mmcf"; break;
    case 259: ret = "gukg"; break;
    case 260: ret = "rujg"; break;
    case 261: ret = "takg"; break;
    case 262: ret = "mirg"; break;
    case 263: ret = "mmcg"; break;
    case 264: ret = "gukh"; break;
    case 265: ret = "rujh"; break;
    case 266: ret = "takh"; break;
    case 267: ret = "mirh"; break;
    case 268: ret = "mmch"; break;
    case 269: ret = "ruji"; break;
    case 270: ret = "taki"; break;
    case 271: ret = "miri"; break;
    case 272: ret = "mmci"; break;
    case 273: ret = "rujj"; break;
    case 274: ret = "takj"; break;
    case 275: ret = "mirj"; break;
    case 276: ret = "mmcj"; break;
    case 277: ret = "chardokb"; break;
    case 278: ret = "soldungc"; break;
    case 279: ret = "abysmal"; break;
    case 280: ret = "natimbi"; break;
    case 281: ret = "qinimi"; break;
    case 282: ret = "riwwi"; break;
    case 283: ret = "barindu"; break;
    case 284: ret = "ferubi"; break;
    case 285: ret = "snpool"; break;
    case 286: ret = "snlair"; break;
    case 287: ret = "snplant"; break;
    case 288: ret = "sncrematory"; break;
    case 289: ret = "tipt"; break;
    case 290: ret = "vxed"; break;
    case 291: ret = "yxtta"; break;
    case 292: ret = "uqua"; break;
    case 293: ret = "kodtaz"; break;
    case 294: ret = "ikkinz"; break;
    case 295: ret = "qvic"; break;
    case 296: ret = "inktuta"; break;
    case 297: ret = "txevu"; break;
    case 298: ret = "tacvi"; break;
    case 299: ret = "qvicb"; break;
    case 300: ret = "wallofslaughter"; break;
    case 301: ret = "bloodfields"; break;
    case 302: ret = "draniksscar"; break;
    case 303: ret = "causeway"; break;
    case 304: ret = "chambersa"; break;
    case 305: ret = "chambersb"; break;
    case 306: ret = "chambersc"; break;
    case 307: ret = "chambersd"; break;
    case 308: ret = "chamberse"; break;
    case 309: ret = "chambersf"; break;
    case 316: ret = "provinggrounds"; break;
    case 317: ret = "anguish"; break;
    case 318: ret = "dranikhollowsa"; break;
    case 319: ret = "dranikhollowsb"; break;
    case 320: ret = "dranikhollowsc"; break;
    case 328: ret = "dranikcatacombsa"; break;
    case 329: ret = "dranikcatacombsb"; break;
    case 330: ret = "dranikcatacombsc"; break;
    case 331: ret = "draniksewersa"; break;
    case 332: ret = "draniksewersb"; break;
    case 333: ret = "draniksewersc"; break;
    case 334: ret = "riftseekers"; break;
    case 335: ret = "harbingers"; break;
    case 336: ret = "dranik"; break;
    case 337: ret = "broodlands"; break;
    case 338: ret = "stillmoona"; break;
    case 339: ret = "stillmoonb"; break;
    case 340: ret = "thundercrest"; break;
    case 341: ret = "delvea"; break;
    case 342: ret = "delveb"; break;
    case 343: ret = "thenest"; break;
    case 344: ret = "guildlobby"; break;
    case 345: ret = "guildhall"; break;
    case 346: ret = "barter"; break;
    case 347: ret = "illsalin"; break;
    case 348: ret = "illsalina"; break;
    case 349: ret = "illsalinb"; break;
    case 350: ret = "illsalinc"; break;
    case 351: ret = "dreadspire"; break;
    case 354: ret = "drachnidhive"; break;
    case 355: ret = "drachnidhivea"; break;
    case 356: ret = "drachnidhiveb"; break;
    case 357: ret = "drachnidhivec"; break;
    case 358: ret = "westkorlach"; break;
    case 359: ret = "westkorlacha"; break;
    case 360: ret = "westkorlachb"; break;
    case 361: ret = "westkorlachc"; break;
    case 362: ret = "eastkorlach"; break;
    case 363: ret = "eastkorlacha"; break;
    case 364: ret = "shadowspine"; break;
    case 365: ret = "corathus"; break;
    case 366: ret = "corathusa"; break;
    case 367: ret = "corathusb"; break;
    case 368: ret = "nektulosa"; break;
    case 369: ret = "arcstone"; break;
    case 370: ret = "relic"; break;
    case 371: ret = "skylance"; break;
    case 372: ret = "devastation"; break;
    case 373: ret = "devastationa"; break;
    case 374: ret = "rage"; break;
    case 375: ret = "ragea"; break;
    case 376: ret = "takishruins"; break;
    case 377: ret = "takishruinsa"; break;
    case 378: ret = "elddar"; break;
    case 379: ret = "elddara"; break;
    case 380: ret = "theater"; break;
    case 381: ret = "theatera"; break;
    case 382: ret = "freeporteast"; break;
    case 383: ret = "freeportwest"; break;
    case 384: ret = "freeportsewers"; break;
    case 385: ret = "freeportacademy"; break;
    case 386: ret = "freeporttemple"; break;
    case 387: ret = "freeportmilitia"; break;
    case 388: ret = "freeportarena"; break;
    case 389: ret = "freeportcityhall"; break;
    case 390: ret = "freeporttheater"; break;
    case 391: ret = "freeporthall"; break;
    case 392: ret = "northro"; break;
    case 393: ret = "southro"; break;
    case 394: ret = "crescent"; break;
    case 395: ret = "moors"; break;
    case 396: ret = "stonehive"; break;
    case 397: ret = "mesa"; break;
    case 398: ret = "roost"; break;
    case 399: ret = "steppes"; break;
    case 400: ret = "icefall"; break;
    case 401: ret = "valdeholm"; break;
    case 402: ret = "frostcrypt"; break;
    case 403: ret = "sunderock"; break;
    case 404: ret = "vergalid"; break;
    case 405: ret = "direwind"; break;
    case 406: ret = "ashengate"; break;
    case 407: ret = "highpasshold"; break;
    case 408: ret = "commonlands"; break;
    case 409: ret = "oceanoftears"; break;
    case 410: ret = "kithforest"; break;
    case 411: ret = "befallenb"; break;
    case 412: ret = "highpasskeep"; break;
    case 413: ret = "innothuleb"; break;
    case 414: ret = "toxxulia"; break;
    case 415: ret = "mistythicket"; break;
    case 416: ret = "kattacastrum"; break;
    case 417: ret = "thalassius"; break;
    case 418: ret = "atiiki"; break;
    case 419: ret = "zhisza"; break;
    case 420: ret = "silyssar"; break;
    case 421: ret = "solteris"; break;
    case 422: ret = "barren"; break;
    case 423: ret = "buriedsea"; break;
    case 424: ret = "jardelshook"; break;
    case 425: ret = "monkeyrock"; break;
    case 426: ret = "suncrest"; break;
    case 427: ret = "deadbone"; break;
    case 428: ret = "blacksail"; break;
    case 429: ret = "maidensgrave"; break;
    case 430: ret = "redfeather"; break;
    case 431: ret = "shipmvp"; break;
    case 432: ret = "shipmvu"; break;
    case 433: ret = "shippvu"; break;
    case 434: ret = "shipuvu"; break;
    case 435: ret = "shipmvm"; break;
    case 436: ret = "mechanotus"; break;
    case 437: ret = "mansion"; break;
    case 438: ret = "steamfactory"; break;
    case 439: ret = "shipworkshop"; break;
    case 440: ret = "gyrospireb"; break;
    case 441: ret = "gyrospirez"; break;
    case 442: ret = "dragonscale"; break;
    case 443: ret = "lopingplains"; break;
    case 444: ret = "hillsofshade"; break;
    case 445: ret = "bloodmoon"; break;
    case 446: ret = "crystallos"; break;
    case 447: ret = "guardian"; break;
    case 448: ret = "steamfontmts"; break;
    case 449: ret = "cryptofshade"; break;
    case 451: ret = "dragonscaleb"; break;
    case 452: ret = "oldfieldofbone"; break;
    case 453: ret = "oldkaesoraa"; break;
    case 454: ret = "oldkaesorab"; break;
    case 455: ret = "oldkurn"; break;
    case 456: ret = "oldkithicor"; break;
    case 457: ret = "oldcommons"; break;
    case 458: ret = "oldhighpass"; break;
    case 459: ret = "thevoida"; break;
    case 460: ret = "thevoidb"; break;
    case 461: ret = "thevoidc"; break;
    case 462: ret = "thevoidd"; break;
    case 463: ret = "thevoide"; break;
    case 464: ret = "thevoidf"; break;
    case 465: ret = "thevoidg"; break;
    case 466: ret = "oceangreenhills"; break;
    case 467: ret = "oceangreenvillage"; break;
    case 468: ret = "oldblackburrow"; break;
    case 469: ret = "bertoxtemple"; break;
    case 470: ret = "discord"; break;
    case 471: ret = "discordtower"; break;
    case 472: ret = "oldbloodfield"; break;
    case 473: ret = "precipiceofwar"; break;
    case 474: ret = "olddranik"; break;
    case 475: ret = "toskirakk"; break;
    case 476: ret = "korascian"; break;
    case 477: ret = "rathechamber"; break;
    case 480: ret = "brellsrest"; break;
    case 481: ret = "fungalforest"; break;
    case 482: ret = "underquarry"; break;
    case 483: ret = "coolingchamber"; break;
    case 484: ret = "shiningcity"; break;
    case 485: ret = "arthicrex"; break;
    case 486: ret = "foundation"; break;
    case 487: ret = "lichencreep"; break;
    case 488: ret = "pellucid"; break;
    case 489: ret = "stonesnake"; break;
    case 490: ret = "brellstemple"; break;
    case 491: ret = "convorteum"; break;
    case 492: ret = "brellsarena"; break;
    case 493: ret = "weddingchapel"; break;
    case 494: ret = "weddingchapeldark"; break;
    case 495: ret = "dragoncrypt"; break;
    case 700: ret = "feerrott2"; break;
    case 701: ret = "thulehouse1"; break;
    case 702: ret = "thulehouse2"; break;
    case 703: ret = "housegarden"; break;
    case 704: ret = "thulelibrary"; break;
    case 705: ret = "well"; break;
    case 706: ret = "fallen"; break;
    case 707: ret = "morellcastle"; break;
    case 708: ret = "somnium"; break;
    case 709: ret = "alkabormare"; break;
    case 710: ret = "miragulmare"; break;
    case 711: ret = "thuledream"; break;
    case 712: ret = "neighborhood"; break;
    case 724: ret = "argath"; break;
    case 725: ret = "arelis"; break;
    case 726: ret = "sarithcity"; break;
    case 727: ret = "rubak"; break;
    case 728: ret = "beastdomain"; break;
    case 729: ret = "resplendent"; break;
    case 730: ret = "pillarsalra"; break;
    case 731: ret = "windsong"; break;
    case 732: ret = "cityofbronze"; break;
    case 733: ret = "sepulcher"; break;
    case 734: ret = "eastsepulcher"; break;
    case 735: ret = "westsepulcher"; break;
    case 752: ret = "shardslanding"; break;
    case 753: ret = "xorbb"; break;
    case 754: ret = "kaelshard"; break;
    case 755: ret = "eastwastesshard"; break;
    case 756: ret = "crystalshard"; break;
    case 757: ret = "breedinggrounds"; break;
    case 758: ret = "eviltree"; break;
    case 759: ret = "grelleth"; break;
    case 760: ret = "chapterhouse"; break;
    case 996: ret = "arttest"; break;
    case 998: ret = "fhalls"; break;
    case 999: ret = "apprentice"; break;
    }
    
    return ret;
}

const char* zone_long_name_by_id(int id)
{
    const char* ret;
    
    switch (id)
    {
    default:
    case   1: ret = "South Qeynos"; break;
    case   2: ret = "North Qeynos"; break;
    case   3: ret = "The Surefall Glade"; break;
    case   4: ret = "The Qeynos Hills"; break;
    case   5: ret = "Highpass Hold"; break;
    case   6: ret = "High Keep"; break;
    case   8: ret = "North Freeport"; break;
    case   9: ret = "West Freeport"; break;
    case  10: ret = "East Freeport"; break;
    case  11: ret = "The Liberated Citadel of Runnyeye"; break;
    case  12: ret = "The Western Plains of Karana"; break;
    case  13: ret = "The Northern Plains of Karana"; break;
    case  14: ret = "The Southern Plains of Karana"; break;
    case  15: ret = "Eastern Plains of Karana"; break;
    case  16: ret = "Gorge of King Xorbb"; break;
    case  17: ret = "Blackburrow"; break;
    case  18: ret = "The Lair of the Splitpaw"; break;
    case  19: ret = "Rivervale"; break;
    case  20: ret = "Kithicor Forest"; break;
    case  21: ret = "West Commonlands"; break;
    case  22: ret = "East Commonlands"; break;
    case  23: ret = "The Erudin Palace"; break;
    case  24: ret = "Erudin"; break;
    case  25: ret = "The Nektulos Forest"; break;
    case  26: ret = "Sunset Home"; break;
    case  27: ret = "The Lavastorm Mountains"; break;
    case  28: ret = "Nektropos"; break;
    case  29: ret = "Halas"; break;
    case  30: ret = "Everfrost Peaks"; break;
    case  31: ret = "Solusek's Eye"; break;
    case  32: ret = "Nagafen's Lair"; break;
    case  33: ret = "Misty Thicket"; break;
    case  34: ret = "Northern Desert of Ro"; break;
    case  35: ret = "Southern Desert of Ro"; break;
    case  36: ret = "Befallen"; break;
    case  37: ret = "Oasis of Marr"; break;
    case  38: ret = "Toxxulia Forest"; break;
    case  39: ret = "The Hole"; break;
    case  40: ret = "Neriak - Foreign Quarter"; break;
    case  41: ret = "Neriak - Commons"; break;
    case  42: ret = "Neriak - 3rd Gate"; break;
    case  43: ret = "Neriak Palace"; break;
    case  44: ret = "Najena"; break;
    case  45: ret = "The Qeynos Aqueduct System"; break;
    case  46: ret = "Innothule Swamp"; break;
    case  47: ret = "The Feerrott"; break;
    case  48: ret = "Accursed Temple of CazicThule"; break;
    case  49: ret = "Oggok"; break;
    case  50: ret = "The Rathe Mountains"; break;
    case  51: ret = "Lake Rathetear"; break;
    case  52: ret = "Grobb"; break;
    case  53: ret = "Aviak Village"; break;
    case  54: ret = "The Greater Faydark"; break;
    case  55: ret = "Ak'Anon"; break;
    case  56: ret = "Steamfont Mountains"; break;
    case  57: ret = "The Lesser Faydark"; break;
    case  58: ret = "Crushbone"; break;
    case  59: ret = "The Castle of Mistmoore"; break;
    case  60: ret = "South Kaladim"; break;
    case  61: ret = "Northern Felwithe"; break;
    case  62: ret = "Southern Felwithe"; break;
    case  63: ret = "The Estate of Unrest"; break;
    case  64: ret = "Kedge Keep"; break;
    case  65: ret = "The City of Guk"; break;
    case  66: ret = "The Ruins of Old Guk"; break;
    case  67: ret = "North Kaladim"; break;
    case  68: ret = "Butcherblock Mountains"; break;
    case  69: ret = "Ocean of Tears"; break;
    case  70: ret = "Dagnor's Cauldron"; break;
    case  71: ret = "The Plane of Sky"; break;
    case  72: ret = "The Plane of Fear"; break;
    case  73: ret = "The Permafrost Caverns"; break;
    case  74: ret = "Kerra Isle"; break;
    case  75: ret = "Paineel"; break;
    case  76: ret = "Plane of Hate"; break;
    case  77: ret = "The Arena"; break;
    case  78: ret = "The Field of Bone"; break;
    case  79: ret = "The Warsliks Woods"; break;
    case  80: ret = "The Temple of Solusek Ro"; break;
    case  81: ret = "The Temple of Droga"; break;
    case  82: ret = "Cabilis West"; break;
    case  83: ret = "The Swamp of No Hope"; break;
    case  84: ret = "Firiona Vie"; break;
    case  85: ret = "Lake of Ill Omen"; break;
    case  86: ret = "The Dreadlands"; break;
    case  87: ret = "The Burning Wood"; break;
    case  88: ret = "Kaesora"; break;
    case  89: ret = "The Ruins of Sebilis"; break;
    case  90: ret = "The City of Mist"; break;
    case  91: ret = "The Skyfire Mountains"; break;
    case  92: ret = "Frontier Mountains"; break;
    case  93: ret = "The Overthere"; break;
    case  94: ret = "The Emerald Jungle"; break;
    case  95: ret = "Trakanon's Teeth"; break;
    case  96: ret = "Timorous Deep"; break;
    case  97: ret = "Kurn's Tower"; break;
    case  98: ret = "Erud's Crossing"; break;
    case 100: ret = "The Stonebrunt Mountains"; break;
    case 101: ret = "The Warrens"; break;
    case 102: ret = "Karnor's Castle"; break;
    case 103: ret = "Chardok"; break;
    case 104: ret = "The Crypt of Dalnir"; break;
    case 105: ret = "The Howling Stones"; break;
    case 106: ret = "Cabilis East"; break;
    case 107: ret = "The Mines of Nurga"; break;
    case 108: ret = "Veeshan's Peak"; break;
    case 109: ret = "Veksar"; break;
    case 110: ret = "The Iceclad Ocean"; break;
    case 111: ret = "The Tower of Frozen Shadow"; break;
    case 112: ret = "Velketor's Labyrinth"; break;
    case 113: ret = "Kael Drakkel"; break;
    case 114: ret = "Skyshrine"; break;
    case 115: ret = "The City of Thurgadin"; break;
    case 116: ret = "Eastern Wastes"; break;
    case 117: ret = "Cobaltscar"; break;
    case 118: ret = "The Great Divide"; break;
    case 119: ret = "The Wakening Land"; break;
    case 120: ret = "The Western Wastes"; break;
    case 121: ret = "The Crystal Caverns"; break;
    case 123: ret = "Dragon Necropolis"; break;
    case 124: ret = "The Temple of Veeshan"; break;
    case 125: ret = "Siren's Grotto"; break;
    case 126: ret = "The Plane of Mischief"; break;
    case 127: ret = "The Plane of Growth"; break;
    case 128: ret = "The Sleeper's Tomb"; break;
    case 129: ret = "Icewell Keep"; break;
    case 130: ret = "Marauders Mire"; break;
    case 150: ret = "Shadow Haven"; break;
    case 151: ret = "The Bazaar"; break;
    case 152: ret = "Nexus"; break;
    case 153: ret = "The Echo Caverns"; break;
    case 154: ret = "The Acrylia Caverns"; break;
    case 155: ret = "The City of Shar Vahl"; break;
    case 156: ret = "The Paludal Caverns"; break;
    case 157: ret = "The Fungus Grove"; break;
    case 158: ret = "Vex Thal"; break;
    case 159: ret = "Sanctus Seru"; break;
    case 160: ret = "Katta Castellum"; break;
    case 161: ret = "Netherbian Lair"; break;
    case 162: ret = "Ssraeshza Temple"; break;
    case 163: ret = "Grieg's End"; break;
    case 164: ret = "The Deep"; break;
    case 165: ret = "Shadeweaver's Thicket"; break;
    case 166: ret = "Hollowshade Moor"; break;
    case 167: ret = "Grimling Forest"; break;
    case 168: ret = "Marus Seru"; break;
    case 169: ret = "Mons Letalis"; break;
    case 170: ret = "The Twilight Sea"; break;
    case 171: ret = "The Grey"; break;
    case 172: ret = "The Tenebrous Mountains"; break;
    case 173: ret = "The Maiden's Eye"; break;
    case 174: ret = "The Dawnshroud Peaks"; break;
    case 175: ret = "The Scarlet Desert"; break;
    case 176: ret = "The Umbral Plains"; break;
    case 179: ret = "The Akheva Ruins"; break;
    case 180: ret = "The Arena Two"; break;
    case 181: ret = "The Jaggedpine Forest"; break;
    case 182: ret = "Nedaria's Landing"; break;
    case 183: ret = "EverQuest Tutorial"; break;
    case 184: ret = "Loading Zone"; break;
    case 185: ret = "New Loading Zone"; break;
    case 186: ret = "The Plane of Hate"; break;
    case 187: ret = "Shadowrest"; break;
    case 188: ret = "The Mines of Gloomingdeep"; break;
    case 189: ret = "The Mines of Gloomingdeep"; break;
    case 190: ret = "Loading"; break;
    case 200: ret = "The Crypt of Decay"; break;
    case 201: ret = "The Plane of Justice"; break;
    case 202: ret = "The Plane of Knowledge"; break;
    case 203: ret = "The Plane of Tranquility"; break;
    case 204: ret = "The Plane of Nightmares"; break;
    case 205: ret = "The Plane of Disease"; break;
    case 206: ret = "The Plane of Innovation"; break;
    case 207: ret = "Torment, the Plane of Pain"; break;
    case 208: ret = "The Plane of Valor"; break;
    case 209: ret = "Bastion of Thunder"; break;
    case 210: ret = "The Plane of Storms"; break;
    case 211: ret = "The Halls of Honor"; break;
    case 212: ret = "The Tower of Solusek Ro"; break;
    case 213: ret = "Plane of War"; break;
    case 214: ret = "Drunder, the Fortress of Zek"; break;
    case 215: ret = "The Plane of Air"; break;
    case 216: ret = "The Plane of Water"; break;
    case 217: ret = "The Plane of Fire"; break;
    case 218: ret = "The Plane of Earth"; break;
    case 219: ret = "The Plane of Time A"; break;
    case 220: ret = "The Temple of Marr"; break;
    case 221: ret = "The Lair of Terris Thule"; break;
    case 222: ret = "The Plane of Earth"; break;
    case 223: ret = "The Plane of Time B"; break;
    case 224: ret = "The Gulf of Gunthak"; break;
    case 225: ret = "Dulak's Harbor"; break;
    case 226: ret = "The Torgiran Mines"; break;
    case 227: ret = "The Crypt of Nadox"; break;
    case 228: ret = "Hate's Fury"; break;
    case 229: ret = "Deepest Guk: Cauldron of Lost Souls"; break;
    case 230: ret = "The Rujarkian Hills: Bloodied Quarries"; break;
    case 231: ret = "Takish-Hiz: Sunken Library"; break;
    case 232: ret = "Miragul's Menagerie: Silent Gallery"; break;
    case 233: ret = "Mistmoore's Catacombs: Forlorn Caverns"; break;
    case 234: ret = "The Drowning Crypt"; break;
    case 235: ret = "The Rujarkian Hills: Halls of War"; break;
    case 236: ret = "Takish-Hiz: Shifting Tower"; break;
    case 237: ret = "Miragul's Menagerie: Frozen Nightmare"; break;
    case 238: ret = "Mistmoore's Catacombs: Dreary Grotto"; break;
    case 239: ret = "Deepest Guk: Ancient Aqueducts"; break;
    case 240: ret = "The Rujarkian Hills: Wind Bridges"; break;
    case 241: ret = "Takish-Hiz: Fading Temple"; break;
    case 242: ret = "The Spider Den"; break;
    case 243: ret = "Mistmoore's Catacombs: Struggles within the Progeny"; break;
    case 244: ret = "The Mushroom Grove"; break;
    case 245: ret = "The Rujarkian Hills: Prison Break"; break;
    case 246: ret = "Takish-Hiz: Royal Observatory"; break;
    case 247: ret = "Miragul's Menagerie: Hushed Banquet"; break;
    case 248: ret = "Mistmoore's Catacombs: Chambers of Eternal Affliction"; break;
    case 249: ret = "Deepest Guk: The Curse Reborn"; break;
    case 250: ret = "The Rujarkian Hills: Drudge Hollows"; break;
    case 251: ret = "Takish-Hiz: River of Recollection"; break;
    case 252: ret = "The Frosted Halls"; break;
    case 253: ret = "Mistmoore's Catacombs: Sepulcher of the Damned"; break;
    case 254: ret = "Deepest Guk: Chapel of the Witnesses"; break;
    case 255: ret = "The Rujarkian Hills: Fortified Lair of the Taskmasters"; break;
    case 256: ret = "Takish-Hiz: Sandfall Corridors"; break;
    case 257: ret = "The Forgotten Wastes"; break;
    case 258: ret = "Mistmoore's Catacombs: Scion Lair of Fury"; break;
    case 259: ret = "The Root Garden"; break;
    case 260: ret = "The Rujarkian Hills: Hidden Vale of Deceit"; break;
    case 261: ret = "Takish-Hiz: Balancing Chamber"; break;
    case 262: ret = "Miragul's Menagerie: Heart of the Menagerie"; break;
    case 263: ret = "Mistmoore's Catacombs: Cesspits of Putrescence"; break;
    case 264: ret = "Deepest Guk: Accursed Sanctuary"; break;
    case 265: ret = "The Rujarkian Hills: Blazing Forge"; break;
    case 266: ret = "Takish-Hiz: Sweeping Tides"; break;
    case 267: ret = "The Morbid Laboratory"; break;
    case 268: ret = "Mistmoore's Catacombs: Aisles of Blood"; break;
    case 269: ret = "The Rujarkian Hills: Arena of Chance"; break;
    case 270: ret = "Takish-Hiz: Antiquated Palace"; break;
    case 271: ret = "The Theater of Imprisoned Horror"; break;
    case 272: ret = "Mistmoore's Catacombs: Halls of Sanguinary Rites"; break;
    case 273: ret = "The Rujarkian Hills: Barracks of War"; break;
    case 274: ret = "Takish-Hiz: Prismatic Corridors"; break;
    case 275: ret = "Miragul's Menagerie: Grand Library"; break;
    case 276: ret = "Mistmoore's Catacombs: Infernal Sanctuary"; break;
    case 277: ret = "Chardok: The Halls of Betrayal"; break;
    case 278: ret = "The Caverns of Exile"; break;
    case 279: ret = "The Abysmal Sea"; break;
    case 280: ret = "Natimbi, the Broken Shores"; break;
    case 281: ret = "Qinimi, Court of Nihilia"; break;
    case 282: ret = "Riwwi, Coliseum of Games"; break;
    case 283: ret = "Barindu, Hanging Gardens"; break;
    case 284: ret = "Ferubi, Forgotten Temple of Taelosia"; break;
    case 285: ret = "Sewers of Nihilia, Pool of Sludg"; break;
    case 286: ret = "Sewers of Nihilia, Lair of Trapp"; break;
    case 287: ret = "Sewers of Nihilia, Purifying Pla"; break;
    case 288: ret = "Sewers of Nihilia, Emanating Cre"; break;
    case 289: ret = "Tipt, Treacherous Crags"; break;
    case 290: ret = "Vxed, the Crumbling Caverns"; break;
    case 291: ret = "Yxtta, Pulpit of Exiles"; break;
    case 292: ret = "Uqua, the Ocean God Chantry"; break;
    case 293: ret = "Kod'Taz, Broken Trial Grounds"; break;
    case 294: ret = "Ikkinz, Chambers of Transcendence"; break;
    case 295: ret = "Qvic, Prayer Grounds of Calling"; break;
    case 296: ret = "Inktu'Ta, the Unmasked Chapel"; break;
    case 297: ret = "Txevu, Lair of the Elite"; break;
    case 298: ret = "Tacvi, The Broken Temple"; break;
    case 299: ret = "Qvic, the Hidden Vault"; break;
    case 300: ret = "Wall of Slaughter"; break;
    case 301: ret = "The Bloodfields"; break;
    case 302: ret = "Dranik's Scar"; break;
    case 303: ret = "Nobles' Causeway"; break;
    case 304: ret = "Muramite Proving Grounds A"; break;
    case 305: ret = "Muramite Proving Grounds B"; break;
    case 306: ret = "Muramite Proving Grounds C"; break;
    case 307: ret = "Muramite Proving Grounds D"; break;
    case 308: ret = "Muramite Proving Grounds E"; break;
    case 309: ret = "Muramite Proving Grounds F"; break;
    case 316: ret = "Muramite Proving Grounds G"; break;
    case 317: ret = "Anguish, the Fallen Palace"; break;
    case 318: ret = "Dranik's Hollows A"; break;
    case 319: ret = "Dranik's Hollows B"; break;
    case 320: ret = "Dranik's Hollows C"; break;
    case 328: ret = "Catacombs of Dranik A"; break;
    case 329: ret = "Catacombs of Dranik B"; break;
    case 330: ret = "Catacombs of Dranik C"; break;
    case 331: ret = "Sewers of Dranik A"; break;
    case 332: ret = "Sewers of Dranik B"; break;
    case 333: ret = "Sewers of Dranik C"; break;
    case 334: ret = "Riftseekers' Sanctum"; break;
    case 335: ret = "Harbinger's Spire"; break;
    case 336: ret = "The Ruined City of Dranik"; break;
    case 337: ret = "The Broodlands"; break;
    case 338: ret = "Stillmoon Temple"; break;
    case 339: ret = "The Ascent"; break;
    case 340: ret = "Thundercrest Isles"; break;
    case 341: ret = "Lavaspinner's Lair"; break;
    case 342: ret = "Tirranun's Delve"; break;
    case 343: ret = "The Nest"; break;
    case 344: ret = "Guild Lobby"; break;
    case 345: ret = "Guild Hall"; break;
    case 346: ret = "The Barter Hall"; break;
    case 347: ret = "Ruins of Illsalin"; break;
    case 348: ret = "Illsalin Marketplace"; break;
    case 349: ret = "Temple of Korlach"; break;
    case 350: ret = "The Nargil Pits"; break;
    case 351: ret = "Dreadspire Keep"; break;
    case 354: ret = "The Hive"; break;
    case 355: ret = "The Hatchery"; break;
    case 356: ret = "The Cocoons"; break;
    case 357: ret = "Queen Sendaii`s Lair"; break;
    case 358: ret = "Stoneroot Falls"; break;
    case 359: ret = "Prince's Manor"; break;
    case 360: ret = "Caverns of the Lost"; break;
    case 361: ret = "Lair of the Korlach"; break;
    case 362: ret = "The Undershore"; break;
    case 363: ret = "Snarlstone Dens"; break;
    case 364: ret = "Shadow Spine"; break;
    case 365: ret = "Corathus Creep"; break;
    case 366: ret = "Sporali Caverns"; break;
    case 367: ret = "The Corathus Mines"; break;
    case 368: ret = "Shadowed Grove"; break;
    case 369: ret = "Arcstone, Isle of Spirits"; break;
    case 370: ret = "Relic, the Artifact City"; break;
    case 371: ret = "Skylance"; break;
    case 372: ret = "The Devastation"; break;
    case 373: ret = "The Seething Wall"; break;
    case 374: ret = "Sverag, Stronghold of Rage"; break;
    case 375: ret = "Razorthorn, Tower of Sullon Zek"; break;
    case 376: ret = "Ruins of Takish-Hiz"; break;
    case 377: ret = "The Root of Ro"; break;
    case 378: ret = "The Elddar Forest"; break;
    case 379: ret = "Tunare's Shrine"; break;
    case 380: ret = "Theater of Blood"; break;
    case 381: ret = "Deathknell, Tower of Dissonance"; break;
    case 382: ret = "East Freeport"; break;
    case 383: ret = "West Freeport"; break;
    case 384: ret = "Freeport Sewers"; break;
    case 385: ret = "Academy of Arcane Sciences"; break;
    case 386: ret = "Temple of Marr"; break;
    case 387: ret = "Freeport Militia House: My Precious"; break;
    case 388: ret = "Arena"; break;
    case 389: ret = "City Hall"; break;
    case 390: ret = "Theater of the Tranquil"; break;
    case 391: ret = "Hall of Truth: Bounty"; break;
    case 392: ret = "North Desert of Ro"; break;
    case 393: ret = "South Desert of Ro"; break;
    case 394: ret = "Crescent Reach"; break;
    case 395: ret = "Blightfire Moors"; break;
    case 396: ret = "Stone Hive"; break;
    case 397: ret = "Goru`kar Mesa"; break;
    case 398: ret = "Blackfeather Roost"; break;
    case 399: ret = "The Steppes"; break;
    case 400: ret = "Icefall Glacier"; break;
    case 401: ret = "Valdeholm"; break;
    case 402: ret = "Frostcrypt, Throne of the Shade King"; break;
    case 403: ret = "Sunderock Springs"; break;
    case 404: ret = "Vergalid Mines"; break;
    case 405: ret = "Direwind Cliffs"; break;
    case 406: ret = "Ashengate, Reliquary of the Scale"; break;
    case 407: ret = "Highpass Hold"; break;
    case 408: ret = "The Commonlands"; break;
    case 409: ret = "The Ocean of Tears"; break;
    case 410: ret = "Kithicor Forest"; break;
    case 411: ret = "Befallen"; break;
    case 412: ret = "HighKeep"; break;
    case 413: ret = "The Innothule Swamp"; break;
    case 414: ret = "Toxxulia Forest"; break;
    case 415: ret = "The Misty Thicket"; break;
    case 416: ret = "Katta Castrum"; break;
    case 417: ret = "Thalassius, the Coral Keep"; break;
    case 418: ret = "Jewel of Atiiki"; break;
    case 419: ret = "Zhisza, the Shissar Sanctuary"; break;
    case 420: ret = "Silyssar, New Chelsith"; break;
    case 421: ret = "Solteris, the Throne of Ro"; break;
    case 422: ret = "Barren Coast"; break;
    case 423: ret = "The Buried Sea"; break;
    case 424: ret = "Jardel's Hook"; break;
    case 425: ret = "Monkey Rock"; break;
    case 426: ret = "Suncrest Isle"; break;
    case 427: ret = "Deadbone Reef"; break;
    case 428: ret = "Blacksail Folly"; break;
    case 429: ret = "Maiden's Grave"; break;
    case 430: ret = "Redfeather Isle"; break;
    case 431: ret = "The Open Sea"; break;
    case 432: ret = "The Open Sea"; break;
    case 433: ret = "The Open Sea"; break;
    case 434: ret = "The Open Sea"; break;
    case 435: ret = "The Open Sea"; break;
    case 436: ret = "Fortress Mechanotus"; break;
    case 437: ret = "Meldrath's Majestic Mansion"; break;
    case 438: ret = "The Steam Factory"; break;
    case 439: ret = "S.H.I.P. Workshop"; break;
    case 440: ret = "Gyrospire Beza"; break;
    case 441: ret = "Gyrospire Zeka"; break;
    case 442: ret = "Dragonscale Hills"; break;
    case 443: ret = "Loping Plains"; break;
    case 444: ret = "Hills of Shade"; break;
    case 445: ret = "Bloodmoon Keep"; break;
    case 446: ret = "Crystallos, Lair of the Awakened"; break;
    case 447: ret = "The Mechamatic Guardian"; break;
    case 448: ret = "The Steamfont Mountains"; break;
    case 449: ret = "Crypt of Shade"; break;
    case 451: ret = "Deepscar's Den"; break;
    case 452: ret = "Field of Scale"; break;
    case 453: ret = "Kaesora Library"; break;
    case 454: ret = "Kaesora Hatchery"; break;
    case 455: ret = "Kurn's Tower"; break;
    case 456: ret = "Bloody Kithicor"; break;
    case 457: ret = "Old Commonlands"; break;
    case 458: ret = "Highpass Hold"; break;
    case 459: ret = "The Void A"; break;
    case 460: ret = "The Void B"; break;
    case 461: ret = "The Void C"; break;
    case 462: ret = "The Void D"; break;
    case 463: ret = "The Void E"; break;
    case 464: ret = "The Void F"; break;
    case 465: ret = "The Void G"; break;
    case 466: ret = "Oceangreen Hills"; break;
    case 467: ret = "Oceangreen Village"; break;
    case 468: ret = "BlackBurrow"; break;
    case 469: ret = "Temple of Bertoxxulous"; break;
    case 470: ret = "Korafax, Home of the Riders"; break;
    case 471: ret = "Citadel of the Worldslayer"; break;
    case 472: ret = "Old Bloodfields"; break;
    case 473: ret = "The Precipice of War"; break;
    case 474: ret = "City of Dranik"; break;
    case 475: ret = "Toskirakk"; break;
    case 476: ret = "Korascian Warrens"; break;
    case 477: ret = "Rathe Council Chamber"; break;
    case 480: ret = "Brell's Rest"; break;
    case 481: ret = "Fungal Forest"; break;
    case 482: ret = "The Underquarry"; break;
    case 483: ret = "The Cooling Chamber"; break;
    case 484: ret = "Kernagir, the Shining City"; break;
    case 485: ret = "Arthicrex"; break;
    case 486: ret = "The Foundation"; break;
    case 487: ret = "Lichen Creep"; break;
    case 488: ret = "Pellucid Grotto"; break;
    case 489: ret = "Volska's Husk"; break;
    case 490: ret = "Brell's Temple"; break;
    case 491: ret = "The Convorteum"; break;
    case 492: ret = "Brell's Arena"; break;
    case 493: ret = "Wedding Chapel"; break;
    case 494: ret = "Wedding Chapel"; break;
    case 495: ret = "Lair of the Risen"; break;
    case 700: ret = "The Feerrott"; break;
    case 701: ret = "House of Thule"; break;
    case 702: ret = "House of Thule, Upper Floors"; break;
    case 703: ret = "The Grounds"; break;
    case 704: ret = "The Library"; break;
    case 705: ret = "The Well"; break;
    case 706: ret = "Erudin Burning"; break;
    case 707: ret = "Morell's Castle"; break;
    case 708: ret = "Sanctum Somnium"; break;
    case 709: ret = "Al'Kabor's Nightmare"; break;
    case 710: ret = "Miragul's Nightmare"; break;
    case 711: ret = "Fear Itself"; break;
    case 712: ret = "Sunrise Hills"; break;
    case 724: ret = "Argath, Bastion of Illdaera"; break;
    case 725: ret = "Valley of Lunanyn"; break;
    case 726: ret = "Sarith, City of Tides"; break;
    case 727: ret = "Rubak Oseka, Temple of the Sea"; break;
    case 728: ret = "Beasts' Domain"; break;
    case 729: ret = "The Resplendent Temple"; break;
    case 730: ret = "Pillars of Alra"; break;
    case 731: ret = "Windsong Sanctuary"; break;
    case 732: ret = "Erillion, City of Bronze"; break;
    case 733: ret = "Sepulcher of Order"; break;
    case 734: ret = "Sepulcher East"; break;
    case 735: ret = "Sepulcher West"; break;
    case 752: ret = "Shard's Landing"; break;
    case 753: ret = "Valley of King Xorbb"; break;
    case 754: ret = "Kael Drakkel: The King's Madness"; break;
    case 755: ret = "East Wastes: Zeixshi-Kar's Awakening"; break;
    case 756: ret = "The Crystal Caverns: Fragment of Fear"; break;
    case 757: ret = "The Breeding Grounds"; break;
    case 758: ret = "Evantil, the Vile Oak"; break;
    case 759: ret = "Grelleth's Palace, the Chateau of Filth"; break;
    case 760: ret = "Chapterhouse of the Fallen"; break;
    case 996: ret = "Art Testing Domain"; break;
    case 998: ret = "The Forgotten Halls"; break;
    case 999: ret = "Designer Apprentice"; break;
    }
    
    return ret;
}
